#!/usr/bin/env python3
"""
Created on Tue Aug  7 10:53:39 2018

@author: Salvatore Palazzo
"""
import time
import pika
import time_uuid

from string import Template

#GLOBALS_CONSTANT
MQ_HOST = "my.domain.com"
HOSTNAME = "192.168.0.1"

#rabbit mq
exchange = "my.domain.checkResult"
connection = pika.BlockingConnection(pika.ConnectionParameters(MQ_HOST))
channel = connection.channel()
channel.confirm_delivery()


#create the message to sent to the queue
def generate_event(event_time, state):
    """
    This is an example of how to create a message to send to the queue
    for a dummy host monitored by nagios for the memory usage
    """
    
    template = Template("""{
      "time": $time,
      "hostname": "$hostname",
      "service": "Memory usage",
      "state": "$state",
      "output": "check output"
    }
    """)

    msg = template.substitute(uuid=time_uuid.TimeUUID.with_utcnow(),
                              time=event_time,
                              hostname=HOSTNAME,
                              service="Memory usage",
                              state=state,
                              output="check output")

    res = channel.basic_publish(exchange=exchange,
                                routing_key='data-generator',
                                properties=pika.BasicProperties(
                                headers={'REQUEST_ID': 'data-generator'},
                                delivery_mode=2),
                                body=msg)
                                
    print("Message generated: " + str(res))
        

#execute
generate_event(int(time.time()),"CRITICAL")
